stages:
  - build
  - deploy

before_script: 
  - npm set registry http://gitlab.com/api/v4/projects/${CI_PROJECT_ID}
  - npm i

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    paths:
      - ./build
    expire_in: 1 day

deploy:
  stage: deploy
  image: node
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm whoami
    - npm publish --verbose
  artifacts:
    paths:
      - /
    expire_in: 1 day

# test:
  #   - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
#   stage: test
#   image: node
#   script:
#     - echo "Testing App"
#     - npm install
#     - CI=true npm test
#     - echo "Test successfully!"